### ISSUE TITLE
mpush在centos7存在虚拟网卡情况下 mp.net.public-host-mapping无效

### ISSUE THREAD

**Issue by HanleyTang** [mpusher/mpush#16]
OS ：centos7 64
mpush ：0.7.1 
mp.net.public-host-mapping 配置后，alloc:9999 一直显示的是虚拟网卡的IP,修改mpush.conf & reference.conf 均无效，执行下面的命令删除虚拟网卡后才能显示mpush.conf配置的IP。

1. virsh net-list
2. virsh net-destroy default
3. virsh net-undefine default
4. systemctl restart libvirtd.service

望确认。

**Comment by ohun** [comment]
最新版本增加了新配置
local-ip=""  //本地ip, 默认取第一个网卡的本地IP
public-ip="" //外网ip, 默认取第一个网卡的外网IP
