### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by i54334** [mpusher/mpush#2]
启动报错：
`[root@localhost bin]# ./mp.sh start
/opt/app/mpush/bin/env-mp.sh:行2: $'\r': 未找到命令
/opt/app/mpush/bin/env-mp.sh:行17: $'\r': 未找到命令
/opt/app/mpush/bin/env-mp.sh:行20: $'\r': 未找到命令
/opt/app/mpush/bin/env-mp.sh:行25: $'\r': 未找到命令
/opt/app/mpush/bin/env-mp.sh:行28: $'\r': 未找到命令
/opt/app/mpush/bin/env-mp.sh:行80: 未预期的符号 `$'do\r'' 附近有语法错误
'opt/app/mpush/bin/env-mp.sh:行80: `do
MPush JMX enabled by default
./mp.sh:行99: cygpath: 未找到命令
Using config: 
mkdir: 无法创建目录"": 没有那个文件或目录

mkdir: 无法创建目录"": 没有那个文件或目录
Starting mpush ... STARTED`

**Comment by ohun** [comment]
你是什么环境，cygwin还是Linux？

**Comment by i54334** [comment]
centos7.1.1503

**Comment by ohun** [comment]
这种情况很可能是git core.autocrlf 导致的，建议手动替换\n\r 为\n试试
