### ISSUE TITLE
window下无法启动服务端

### ISSUE THREAD

**Issue by daniel-007** [mpusher/mpush#4]
下载0.0.4版，执行bin目录下的mp.cmd start 命令，显示如下错误：
Unrecognized option: -jar ../boot.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
貌似没有boot.jar ？ 
尝试修改mp.cmd，改成bin目录下的bootstrap.jar，错误仍然一样。

**Comment by ohun** [comment]
请使用最新版
