### ISSUE TITLE
广播推送不成功

### ISSUE THREAD

**Issue by flykarry** [mpusher/mpush#6]
![qq 20161213115837](https://cloud.githubusercontent.com/assets/14309127/21127157/c9e32ac6-c12b-11e6-943b-3d65752cacdb.jpg)
设置上userId才可以，是哪的问题？

**Comment by ohun** [comment]
请修改网关模式为mp.net.gateway-server-net=tcp 因为udp网关模式下，广播推送使用的是组播，如果网络配置不正确，比如跨网段等是不能收到消息的。
